import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/1beddb9e38.js" crossorigin="anonymous"></script>
      </head>
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <Navbar/>
          <div className="flex-grow">{children}</div>
          <Footer/>
        </div>
        </body>
    </html>
  );
}
